name: Build DayTracker Android APK/AAB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
    # 1️⃣ Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Cache Node modules
    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-modules-

    # 3️⃣ Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # 4️⃣ Install Cordova CLI
    - name: Install Cordova
      run: npm install -g cordova@12

    # 5️⃣ Cache Gradle
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-

    # 6️⃣ Prepare Android platform
    - name: Prepare Android platform
      run: |
        cordova platform rm android || true
        cordova platform add android@12.0.1

    # 7️⃣ Build Release APK
    - name: Build APK
      run: cordova build android --release

    # 8️⃣ Upload APK artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: DayTracker-APK
        path: platforms/android/app/build/outputs/apk/release/*.apk

    # 9️⃣ Build Release AAB
    - name: Build AAB
      run: cordova build android --release -- --packageType=bundle

    # 🔟 Upload AAB artifact
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: DayTracker-AAB
        path: platforms/android/app/build/outputs/bundle/release/*.aab
