name: Day-Tracker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-temurin
      ANDROID_SDK_ROOT: $HOME/Android/Sdk

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js (16.x LTS)
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install project dependencies
      run: npm install

    - name: Ensure gradlew is executable (if present)
      run: |
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew
        fi

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        components: platform-tools, build-tools;33.0.0

    - name: Build Android Debug APK
      run: |
        if [ -f "./gradlew" ]; then
          ./gradlew assembleDebug
        else
          echo "No gradlew found; skipping debug build."
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Day-Tracker-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
