name: Build DayTracker Android APK/AAB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Setup Node.js LTS
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # 3️⃣ Install Cordova CLI
    - name: Install Cordova
      run: npm install -g cordova@12

    # 4️⃣ Setup Java 17 properly
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 5️⃣ Cache Gradle dependencies for faster builds
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-

    # 6️⃣ Prepare Android platform (removes old platform if exists)
    - name: Prepare Android platform
      run: |
        cordova platform rm android || true
        cordova platform add android@12.0.1

    # 7️⃣ Build Release APK
    - name: Build Release APK
      run: cordova build android --release

    # 8️⃣ Upload APK artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: DayTracker-APK
        path: platforms/android/app/build/outputs/apk/release/*.apk

    # 9️⃣ Build Release AAB (bundle)
    - name: Build Release AAB
      run: cordova build android --release -- --packageType=bundle

    # 🔟 Upload AAB artifact
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: DayTracker-AAB
        path: platforms/android/app/build/outputs/bundle/release/*.aab
