name: Build Cordova Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Set up Java JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-

    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: npm-

    - name: Install Cordova
      run: npm install -g cordova

    - name: Install Android SDK and Build Tools
      run: |
        sudo mkdir -p /usr/local/android-sdk
        sudo chown $USER:$USER /usr/local/android-sdk
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools.zip -d /usr/local/android-sdk/cmdline-tools
        mv /usr/local/android-sdk/cmdline-tools/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
        yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/usr/local/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Set Android SDK environment
      run: |
        echo "ANDROID_SDK_ROOT=/usr/local/android-sdk" >> $GITHUB_ENV
        echo "/usr/local/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Install Gradle 7.6
      run: |
        wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
        sudo unzip -d /opt/gradle gradle-7.6-bin.zip
        echo "/opt/gradle/gradle-7.6/bin" >> $GITHUB_PATH

    - name: Force Cordova to use Gradle 7.6
      run: |
        echo "CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL=https://services.gradle.org/distributions/gradle-7.6-bin.zip" >> $GITHUB_ENV

    - name: Add Android platform (force re-install)
      run: |
        cordova platform remove android || true
        cordova platform add android@12.0.1

    - name: Build debug APK
      run: npx cordova build android --debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: day-tracker-apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
