name: Build Cordova Android App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Install project dependencies
        run: npm install

      - name: Add Android platform
        run: npx cordova platform add android@12.0.0

      - name: Install Gradle 8.7 (compatible with Cordova)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: npx cordova build android --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: DayTracker-debug
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
