name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Gradle 7.6
        run: |
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip -q gradle-7.6-bin.zip
          echo "$PWD/gradle-7.6/bin" >> $GITHUB_PATH
          gradle -v

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d $HOME/cmdline-tools
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install project dependencies
        run: npm install

      - name: Add Android platform
        run: cordova platform add android

      - name: Build Android APK
        run: cordova build android --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: platforms/android/app/build/outputs/apk/release/*.apk
